"""Domain constants for AlgoFlow contracts."""

# Workflow status codes
INTENT_STATUS_ACTIVE = 1
INTENT_STATUS_EXECUTING = 2
INTENT_STATUS_SUCCESS = 3
INTENT_STATUS_FAILED = 4
INTENT_STATUS_CANCELLED = 5

INTENT_STATUS_NAMES = {
    INTENT_STATUS_ACTIVE: "ACTIVE",
    INTENT_STATUS_EXECUTING: "EXECUTING",
    INTENT_STATUS_SUCCESS: "SUCCESS",
    INTENT_STATUS_FAILED: "FAILED",
    INTENT_STATUS_CANCELLED: "CANCELLED",
}

# Box and log configuration
BOX_PREFIX_INTENT_LITERAL = b"intent:"
BOX_PREFIX_AUDIT_LITERAL = b"audit:"
BOX_KEY_SEPARATOR_LITERAL = b":"
MAX_WORKFLOW_BYTES_LITERAL = 3584  # TEAL accounts for 4KB limit minus metadata
MAX_AUDIT_LOG_BYTES_LITERAL = 1024

# Global keys
G_OWNER_LITERAL = b"g_owner"
G_KEEPER_LITERAL = b"g_keeper"
G_VERSION_LITERAL = b"g_version"
G_NEXT_INTENT_LITERAL = b"g_next_intent"
G_MIN_COLLATERAL_LITERAL = b"g_min_collat"
G_STORAGE_APP_LITERAL = b"g_storage"
G_FEE_SPLIT_BPS_LITERAL = b"g_fee_bps"
G_EXECUTOR_APP_LITERAL = b"g_executor"

# Event topics for log parsing
LOG_TOPIC_INTENT_CREATED_LITERAL = b"EVENT_INTENT_CREATED"
LOG_TOPIC_INTENT_STATUS_LITERAL = b"EVENT_INTENT_STATUS"
LOG_TOPIC_EXECUTION_RESULT_LITERAL = b"EVENT_EXECUTION"

# Fee bounds
MAX_KEEPER_FEE_BPS = 2000  # 20%
KEEPER_FEE_SCALE = 10_000
