"""Workflow step opcode definitions."""

OPCODE_SWAP = 1
OPCODE_PROVIDE_LIQUIDITY = 2
OPCODE_STAKE = 3
OPCODE_TRANSFER = 4
OPCODE_LEND_SUPPLY = 5
OPCODE_LEND_WITHDRAW = 6
OPCODE_WITHDRAW_LIQUIDITY = 7
OPCODE_UNSTAKE = 8

OPCODE_NAMES = {
    OPCODE_SWAP: "SWAP",
    OPCODE_PROVIDE_LIQUIDITY: "PROVIDE_LIQUIDITY",
    OPCODE_STAKE: "STAKE",
    OPCODE_TRANSFER: "TRANSFER",
    OPCODE_LEND_SUPPLY: "LEND_SUPPLY",
    OPCODE_LEND_WITHDRAW: "LEND_WITHDRAW",
    OPCODE_WITHDRAW_LIQUIDITY: "WITHDRAW_LIQUIDITY",
    OPCODE_UNSTAKE: "UNSTAKE",
}
